package SOLID;

/*
 * 1. HIGH LEVEL MODULES SHOULD NOT DEPEND ON LOW LEVEL MODULES, BOTH SHOULD DEPEND ON ABSTRACTIONS
 * 2. ABSTRACTION SHOULD NOT DEPEND UPON DETAILS. DETIALS SHOULD DEPEND UPON ABSTRACTIONS. 
*/
public class D_Dependency_Inversion_Principle {

}
